name: Local Development Score

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  record-local-score:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: create pem file
      run: |
        echo "${{ secrets.SSH_PEM }}" > ./id_rsa
        chmod 600 ./id_rsa
    - name: add host key to known_hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H ${{ secrets.SSH_ADDRESS }} >> ~/.ssh/known_hosts
    - name: docker compose up
      run: |
        bash init.sh ${{ secrets.SSH_ADDRESS }} ./id_rsa
    - name: run local scoring
      id: running
      run: |
        output=$(bash run.sh)
        echo "$output"
        score=$(echo "$output" | grep "Final Score:" | sed 's/.*Final Score: //')
        echo "score=$score" >> $GITHUB_OUTPUT
    - name: Generate score comment
      run: |
        cat << EOF > score.md
        ### 🤖 Local Development Score

        **Final Score: ${{ steps.running.outputs.score }}**

        Generated by GitHub Actions on commit \`${{ github.sha }}\`
        EOF
        cat score.md
    - name: Create PR comment
      if: github.event_name == 'pull_request'
      run: |
        gh pr comment ${{ github.event.number }} --edit-last --body-file score.md \
        || gh pr comment ${{ github.event.number }} --body-file score.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}